FROM gradle:8.5.0-jdk21-jammy

WORKDIR /app
COPY build.gradle settings.gradle ./
COPY gradle gradle
RUN gradle build -x test || true
CMD ["gradle", "bootRun"]

COPY build.gradle settings.gradle ./
COPY gradle gradle

RUN gradle build -x test || true

CMD ["gradle", "bootRun"]
