# --- DataSource (???) ---
# ? ??? Docker ?? ? ?? ??? ???????.
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# --- JPA/Hibernate (???) ---
# ?? ???? ????, ???? ???? ?? (??)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Logging (???) ---
logging.level.org.hibernate.SQL=error
logging.level.org.springframework.web=INFO


# --- OCI Vault ?? ?? ---
spring.cloud.oci.config.type=instance_principal
spring.cloud.oci.region.static=ap-osaka-1

spring.cloud.oci.vault.enabled=true

spring.cloud.oci.vault.compartment-id=ocid1.tenancy.oc1..aaaaaaaanyhg6va4cy23zi6be5qmizgj3hye57b6quyw4igub2oif52qsl7a

# [??] ???(Vault) ID
spring.cloud.oci.vault.property-sources[0].vault-id=ocid1.vault.oc1.ap-osaka-1.fzuwmeclaab32.abvwsljrqakn3wj5thdh56hvhp5zawuqi5kcfv7lycsfnzre2qolayj4ukoa